// This file is auto-generated by Lovable. Do not modify it.

import { createLovableAuth } from "@lovable.dev/cloud-auth-js";
import { supabase } from "../supabase/client";

// When running locally, the /~oauth/initiate route doesn't exist because it's
// served by Lovable's hosting infrastructure. Point the broker to the production
// URL so the OAuth flow initiates there and redirects back to localhost.
const isLocal = typeof window !== "undefined" && window.location.hostname === "localhost";
const lovableAuth = createLovableAuth(
  isLocal ? { oauthBrokerUrl: "https://openeye.sh/~oauth/initiate" } : undefined,
);

type SignInOptions = {
  redirect_uri?: string;
  extraParams?: Record<string, string>;
};

export const lovable = {
  auth: {
    signInWithOAuth: async (provider: "google" | "apple", opts?: SignInOptions) => {
      const result = await lovableAuth.signInWithOAuth(provider, {
        redirect_uri: opts?.redirect_uri,
        extraParams: {
          ...opts?.extraParams,
        },
      });

      if (result.redirected) {
        return result;
      }

      if (result.error) {
        return result;
      }

      try {
        await supabase.auth.setSession(result.tokens);
      } catch (e) {
        return { error: e instanceof Error ? e : new Error(String(e)) };
      }
      return result;
    },
  },
};
