"""Fleet models package — re-exports all names for backward compatibility."""

from .api import (
    BBox,
    DepthResponse,
    DescribeResponse,
    DetectedObjectResponse,
    DetectResponse,
    ErrorResponse,
    ImageInfoResponse,
    ModelInfo,
    UsageResponse,
)
from .fleet import (
    AlertSeverity,
    AlertType,
    AutoScalingPolicy,
    BatchDeviceRequest,
    CommandStatus,
    CommandType,
    DecommissionRequest,
    DeploymentCreateRequest,
    DeploymentDeviceStatusResponse,
    DeploymentResponse,
    DeploymentStatus,
    DeploymentStrategy,
    DeviceGroupCreateRequest,
    DeviceGroupResponse,
    DeviceRegisterRequest,
    DeviceResponse,
    DeviceStatus,
    DeviceType,
    DeviceUpdateRequest,
    FleetAlertResponse,
    HardwareSpecs,
    HeartbeatRequest,
    HeartbeatResponse,
    MaintenanceWindowCreateRequest,
    MaintenanceWindowResponse,
    OTAUpdateRequest,
    PendingCommand,
    ResourceUsage,
    RolloutStage,
)

__all__ = [
    # Fleet domain
    "AlertSeverity",
    "AlertType",
    "AutoScalingPolicy",
    "BatchDeviceRequest",
    "CommandStatus",
    "CommandType",
    "DecommissionRequest",
    "DeploymentCreateRequest",
    "DeploymentDeviceStatusResponse",
    "DeploymentResponse",
    "DeploymentStatus",
    "DeploymentStrategy",
    "DeviceGroupCreateRequest",
    "DeviceGroupResponse",
    "DeviceRegisterRequest",
    "DeviceResponse",
    "DeviceStatus",
    "DeviceType",
    "DeviceUpdateRequest",
    "FleetAlertResponse",
    "HardwareSpecs",
    "HeartbeatRequest",
    "HeartbeatResponse",
    "MaintenanceWindowCreateRequest",
    "MaintenanceWindowResponse",
    "OTAUpdateRequest",
    "PendingCommand",
    "ResourceUsage",
    "RolloutStage",
    # Hosted API
    "BBox",
    "DepthResponse",
    "DescribeResponse",
    "DetectedObjectResponse",
    "DetectResponse",
    "ErrorResponse",
    "ImageInfoResponse",
    "ModelInfo",
    "UsageResponse",
]
